import Brunch from 'components/Brunch/Brunch';
import Drinks from 'components/Drinks/Drinks';
import Head from 'next/head';

export default function Home() {
  return (
    <main className="container">
      <Head>
        <title>RocketCoffee - Maratona Explorer 3.0</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Brunch />
      <Drinks />
    </main>
  )
}
